version: '3.8'

services:

  # MQTT Broker
  mqtt:
    build:
      context: ./MQTT
    container_name: MQTT
    ports:
      - "1883:1883"
    volumes:
      - ./MQTT/config:/mosquitto/config
      - ./MQTT/data:/mosquitto/data
      - ./MQTT/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - iot-network

  # Facial Recognition service
#  facial_recognition_service:
#    build:
#      context: ./facial_recognition_service
#    container_name: facial_recognition_service
#    depends_on:
#      - mqtt
#    restart: unless-stopped
#    networks:
#      - iot-network


  # Facial Recognition service
  kiosk_service:
    build:
      context: ./kiosk_service
    container_name: kiosk_service
    depends_on:
      - mqtt
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - iot-network



networks:
  iot-network:
    driver: bridge
