version: '3.8'

services:

# MQTT Broker
  mqtt:
    build:
      context: ./MQTT
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./MQTT/config:/mosquitto/config
      - ./MQTT/data:/mosquitto/data
      - ./MQTT/log:/mosquitto/log
      - ./MQTT/certs:/mosquitto/certs
    restart: unless-stopped
    networks:
      - iot-network

# Facial Recognition service
  facial_recognition_service:
    build:
      context: ./facial_recognition_service
    container_name: facial_recognition_service
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - iot-network


# Kiosk service
  kiosk_service:
    build:
      context: ./kiosk_service
    container_name: kiosk_service
    depends_on:
      - mqtt
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - iot-network

# MQTT service
  mqtt_service:
    build:
      context: ./mqtt_service
    container_name: mqtt_service
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - iot-network

# MQTT to LoRa service
#  mqtt_to_lora_service:
#    build:
#      context: ./mqtt_to_lora_service
#    container_name: mqtt_to_lora_service
#    privileged: true
#    devices:
#      - "/dev/spidev0.0:/dev/spidev0.0"
#      - "/dev/gpiomem:/dev/gpiomem"
#    depends_on:
#      - mqtt
#    restart: unless-stopped
#    networks:
#      - iot-network


networks:
  iot-network:
    driver: bridge
